[Controls]
Style=Material

[Universal]
Theme=System
Accent=Red

[Material]
Theme=Light
Accent="#192864"
Primary="#ffffff"

;[Material]
;Theme=Light
;Accent="#0000FF"
;Primary="#0000FF"

